[default_config]
version = "0.10.1"
assembler = "gas"
instruction_set = "x86-64"

[default_config.opts]
compiler = "g++"
compile_flags_txt = [
    "-O0",
    "--std=c++20",
]
diagnostics = true
default_diagnostics = false
